/*
  Warnings:

  - The values [ACCOMMODATIONS_AND_BUILDING,FURNITURE,HOME_AND_ELECTRICALS,MONEY_AND_ENERGY,PERSONAL_CARE_AND_BEAUTY,RECREATION,STATIONERY_AND_PRINTING,TRANSPORT_AND_MACHINE] on the enum `Product_category` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterTable
ALTER TABLE `Product` MODIFY `category` ENUM('FOOD', 'FASHION_AND_WEARS', 'GROCERY_AND_GENERAL', 'HEALTH_AND_WELLNESS', 'HOME_AND_ELECTRICAL_APPLIANCES', 'PERSONAL_SERVICES', 'PRINTING_AND_STATIONERY', 'TECH') NOT NULL;
